version: "3.0"
services:
  server:
    container_name: web_server
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
    tty: true
    working_dir: /app
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - .:/app
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "1", "--threads", "1", "wsgi:app"]
